### PR TITLE
Remove wso2ei-samples script

### PR DESCRIPTION
**Pull request by abeykoon**
## Purpose

User does not try out samples using `wso2ei-samples.sh` file at `[EIHOME]/samples/bin` folder. 
We decided to remove the script as a result. 

## Goals

Remove `wso2ei-samples.sh` file at [EIHOME]/samples/bin

### CODE REVIEW

**Comment by a5anka** [comment]
Why do we say "User does not try out samples using wso2ei-samples.sh"? Doesn't `wso2ei-samples.sh` makes it easier to try out a sample? It reduces the amount of time you have to spend to try out a sample and I think a valuable thing.

**Comment by Vathsan** [comment]
+1 @a5anka
I think the script is useful for the users who want to try the concepts and test the functionality without spending too much time.

**Comment by abeykoon** [comment]
@isudana could you explain the idea behind this as per offline discussion?

**Comment by isudana** [comment]
> @isudana could you explain the idea behind this as per offline discussion?

These samples are not updated over time.
We don't need to give prominence for these samples anymore. 
Starting from sample script and building the rest of the configuration on top of it might lead to issues as well (due to the absence of registry definition, task definition, etc.)

**Pull request merged**
