### PR TITLE
Add JSONPayloadXMLSpecialCharEscapeTest

### PR DESCRIPTION
**Pull request by Drifftr**
## Purpose
This adds the test case for https://github.com/wso2/product-ei/issues/2810

### CODE REVIEW

**Comment by milindaperera** [comment]
Please clean up the description template content if you do not fill them.

**Comment by Drifftr** [comment]
A new change was done to this scenario and will be released with the next synapse release. Test is changed accordingly and we can merge this once new synapse release is done.

**Comment by a5anka** [comment]
@Drifftr Shall we do a synapse release and merge this?

**Comment by Nirothipan** [comment]
Can be merged after upgrading https://github.com/wso2/product-ei/blob/master/pom.xml#L1525 to 2.1.7-wso2v83

**Pull request merged**
